# --- resolve data/ paths relative to repo root ---
import os as _os
_root = _os.path.dirname(_os.path.abspath(__file__))
while not _os.path.isdir(_os.path.join(_root, "data")) and _root != _os.path.dirname(_root):
    _root = _os.path.dirname(_root)
_os.chdir(_os.path.join(_root, "data"))
import json

# Drop the manually audited bad pairs from the merged ground truth.
#
#   ground_truth.jsonl              (merge output, read-only here)
# - rows tagged bad_pair in the audit file
# = ground_truth_clean.jsonl
#
# ground_truth.jsonl is regenerated by merge_ground_truth.py, so this runs as a
# separate downstream step writing its own file rather than editing in place.
#
# Two quirks of the audit file are handled explicitly:
#   1. Some lines have a trailing `// ...` reviewer note after the closing brace,
#      so the file is NOT strict JSONL. Parse with raw_decode and keep the note.
#   2. A few audited pairs are stored in the reverse direction from ground truth
#      (issue and canonical swapped), so matching is on the UNORDERED pair.

GT_FILE = "ground_truth.jsonl"
AUDIT_FILE = "all_retrieval_misses_armA.jsonl"
OUT_FILE = "ground_truth_clean.jsonl"
DROPPED_FILE = "ground_truth_dropped.jsonl"


def load_audit(path):
    """Parse one JSON object per line, tolerating a trailing // comment."""
    decoder = json.JSONDecoder()
    rows = []
    for lineno, line in enumerate(open(path), 1):
        line = line.rstrip("\n")
        if not line.strip():
            continue
        obj, end = decoder.raw_decode(line)
        trailing = line[end:].strip()
        if trailing:
            obj["note"] = trailing.lstrip("/").strip()
        obj["_lineno"] = lineno
        rows.append(obj)
    return rows


def load_jsonl(path):
    return [json.loads(l) for l in open(path) if l.strip()]


audit = load_audit(AUDIT_FILE)
bad = [r for r in audit if r.get("tag") == "bad_pair"]
# unordered key so reverse-direction rows still match
bad_keys = {frozenset({r["pile1_number"], r["canonical_number"]}) for r in bad}

gt = load_jsonl(GT_FILE)
kept, dropped = [], []
for r in gt:
    (dropped if frozenset({r["issue"], r["canonical"]}) in bad_keys else kept).append(r)

for path, rows in ((OUT_FILE, kept), (DROPPED_FILE, dropped)):
    with open(path, "w") as f:
        for r in rows:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")

matched = {frozenset({r["issue"], r["canonical"]}) for r in dropped}
unmatched = bad_keys - matched

print(f"audit rows: {len(audit)}  (bad_pair: {len(bad)}, "
      f"unique unordered pairs: {len(bad_keys)})")
print(f"ground truth: {len(gt)} -> {len(kept)} kept, {len(dropped)} dropped")
print(f"-> {OUT_FILE}")
print(f"-> {DROPPED_FILE}  (the excluded edges, for inspection)")
if unmatched:
    print(f"WARNING: {len(unmatched)} audited bad pair(s) had no ground-truth edge: "
          f"{[sorted(k) for k in unmatched]}")
